# Generated by Django 3.0.6 on 2020-05-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('temperature', models.IntegerField()),
                ('moisture', models.DecimalField(decimal_places=2, max_digits=2)),
                ('light', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
