# Generated by Django 3.0.6 on 2020-05-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20200520_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='light',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='moisture',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
